import type { CommandDrill } from "./command-drills.ts"
import type { ObjectiveId, LabId } from "./curriculum.ts"
import { learningSources } from "./learning/sources.ts"

function drill(
  id: string,
  title: string,
  objectiveId: ObjectiveId,
  scenario: string,
  command: string,
  output: string,
  explanation: string,
  verify: string,
  labId?: LabId,
): CommandDrill {
  return {
    id,
    title,
    objectiveIds: [objectiveId],
    scenario,
    command,
    output,
    objective: verify,
    outputExplanation: explanation,
    verify,
    labId,
    durationMinutes: 5,
    sourceLocators: learningSources(objectiveId),
  }
}

export const extraCommandDrills: readonly CommandDrill[] = [
  drill(
    "mac-learning",
    "Trace a learned MAC",
    "1.13",
    "A frame should reach the workstation in VLAN 40. Recall how to inspect the learned source MAC and outgoing switch port before changing the VLAN.",
    "show mac address-table dynamic",
    "Vlan    Mac Address       Type        Ports\n40      00aa.bbcc.0040    DYNAMIC     Gi0/7",
    "The table scopes the learned MAC to VLAN 40 and port Gi0/7. Dynamic entries are learned from source addresses and can age out; this is not a list of IP routes.",
    "Identify the VLAN, MAC, learned type, and port; confirm the endpoint's actual attachment.",
    "L01",
  ),
  drill(
    "lldp",
    "Read standard discovery",
    "2.3",
    "A mixed-vendor neighbor should appear on the uplink. Recall the standard discovery command and distinguish local from remote port identity.",
    "show lldp neighbors",
    "Device ID       Local Intf    Hold-time  Capability  Port ID\nbranch-switch   Gi0/1         110        B           1/1/24",
    "Gi0/1 is local; 1/1/24 is the neighbor's reported port. B indicates bridge capability in this illustrative format. Advertised identity should be reconciled with inventory, not treated as proof of trust.",
    "Map both cable endpoints and explain what the advertisement establishes.",
    "L07",
  ),
  drill(
    "route-match",
    "Resolve a destination route",
    "3.2",
    "A server at 198.51.100.74 matches several prefixes. Recall how to query the router's selected route for that specific destination.",
    "show ip route 198.51.100.74",
    'Routing entry for 198.51.100.64/26\n  Known via "static", distance 1, metric 0\n  Routing Descriptor Blocks:\n  * 192.0.2.2',
    "The selected /26 covers .64 through .127. The next hop is 192.0.2.2. Compare this more-specific installed match with broader entries; AD compares sources for the same prefix, not different prefix lengths.",
    "Explain why the destination matches this prefix and resolve the next hop.",
    "L09",
  ),
  drill(
    "ipv6-routes",
    "Check IPv6 fallback",
    "3.3",
    "A dual-stack branch has an IPv6 default and a specific remote subnet route. Recall the IPv6 table command and separate its network and default entries.",
    "show ipv6 route",
    "S   2001:DB8:40::/64 [1/0]\n     via FE80::2, GigabitEthernet0/1\nS   ::/0 [1/0]\n     via FE80::2, GigabitEthernet0/1",
    "The /64 is a network route and ::/0 is the default. A link-local next hop requires link context, supplied by the outgoing interface. A table entry alone does not prove the remote return path.",
    "Name each route's scope and test IPv6 reachability in both directions.",
    "L13",
  ),
  drill(
    "ntp",
    "Verify clock synchronization",
    "4.2",
    "An NTP server command has been entered, but logs still disagree. Recall how to inspect synchronization state instead of relying on configuration intent.",
    "show ntp status",
    "Clock is synchronized, stratum 3, reference is 192.0.2.50\nnominal freq is 250.0000 Hz",
    "This illustrative status reports synchronized operation using the listed reference. Stratum represents hierarchy position; it is not independently a guarantee of clock accuracy. Association and source health deserve separate checks.",
    "Identify synchronization state, stratum, and reference, then compare timestamp evidence.",
    "L16",
  ),
  drill(
    "dhcp-relay",
    "Locate the relay helper",
    "4.6",
    "Clients in VLAN 60 need leases from a routed server. Recall how to inspect the helper on the client-facing Layer 3 interface.",
    "show ip interface Vlan60",
    "Vlan60 is up, line protocol is up\n  Internet address is 10.60.0.1/24\n  Helper address is 192.0.2.60",
    "The helper destination is the server path, while 10.60.0.1 identifies the client subnet context. Verify route reachability, scope availability, and return path; a helper line alone cannot prove lease delivery.",
    "Compare helper destination, client subnet, server scope, and a real client lease test.",
    "L14",
  ),
  drill(
    "dhcp-client",
    "Check a dynamic interface address",
    "4.6",
    "A supported router WAN interface is intended to use DHCP. Recall a first command to inspect whether an address was learned and whether the link is operational.",
    "show ip interface brief",
    "Interface              IP-Address      OK? Method Status Protocol\nGigabitEthernet0/1      192.0.2.86      YES DHCP   up     up",
    "Method DHCP indicates the displayed address was obtained dynamically in this illustrative output. Up/up describes interface and line protocol state, not proof of DNS or every remote destination. Lease detail commands vary by platform.",
    "Confirm the learned address and operational state, then verify lease and routing information.",
    "L14",
  ),
  drill(
    "nat",
    "Read a translation mapping",
    "4.1",
    "An inside server should have a static outside representation. Recall how to inspect the actual translation and distinguish inside local from inside global.",
    "show ip nat translations",
    "Pro Inside global      Inside local       Outside local      Outside global\n--- 203.0.113.44        10.44.0.10         ---                ---",
    "The inside host is 10.44.0.10 locally and represented as 203.0.113.44 outside. Static mappings can appear without a current session. Test eligible traffic and the return path before concluding the service is reachable.",
    "Identify both inside address roles and correlate translation with traffic tests.",
    "L15",
  ),
  drill(
    "logging",
    "Interpret a logging threshold",
    "4.5",
    "A log collector receives errors but not informational events. Recall how to inspect destinations and their severity thresholds.",
    "show logging",
    "Syslog logging: enabled\n  Console logging: level debugging\n  Trap logging: level warnings\n  Logging to 192.0.2.70\n%LINK-3-UPDOWN: Interface GigabitEthernet0/2, changed state to down",
    "Warnings is severity 4, so the remote threshold includes 0 through 4. The displayed LINK event is level 3. Console and remote destinations can have different thresholds; log timestamps also depend on clock configuration.",
    "Compare destination thresholds and classify the event's facility, severity, and mnemonic.",
    "L16",
  ),
  drill(
    "ssh",
    "Inspect SSH server state",
    "4.8",
    "A router has keys and local credentials, but remote access still needs validation. Recall how to inspect the SSH server's supported operating version.",
    "show ip ssh",
    "SSH Enabled - version 2.0\nAuthentication timeout: 90 secs; Authentication retries: 2",
    "This shows the SSH server state, version, and authentication limits. It does not establish VTY transport policy, ACL reachability, a successful account login, or correct command permissions.",
    "Verify server state, VTY policy, transport reachability, authentication, and authorization separately.",
    "L17",
  ),
  drill(
    "port-security",
    "Diagnose a secure-port violation",
    "5.7",
    "A client port stopped forwarding after an unexpected device was attached. Recall how to inspect the violation mode and secure state.",
    "show port-security interface GigabitEthernet0/8",
    "Port Security              : Enabled\nPort Status                : Secure-shutdown\nViolation Mode             : Shutdown\nMaximum MAC Addresses      : 1\nTotal MAC Addresses        : 1\nSecurity Violation Count   : 1",
    "Secure-shutdown and shutdown mode are consistent with an error-disabling violation. The count is evidence to investigate, not authorization to remove the control. Confirm the approved endpoint and use the supported recovery process.",
    "Explain state, mode, allowed address count, and violation evidence.",
    "L20",
  ),
  drill(
    "dhcp-snooping",
    "Inspect a lease binding",
    "5.7",
    "ARP inspection needs a trustworthy dynamic host binding. Recall how to inspect DHCP snooping's learned IP/MAC/VLAN/interface association.",
    "show ip dhcp snooping binding",
    "MacAddress          IpAddress     Lease(sec) Type           VLAN Interface\n00:AA:BB:CC:00:60    10.60.0.25    3400       dhcp-snooping  60   Gi0/8",
    "The binding associates this client MAC, leased IP, VLAN, and access port. It is not a list of trusted server uplinks; inspect snooping configuration separately. Static clients need an explicit supported validation plan.",
    "Match the binding to the endpoint and identify what additional trust configuration must be checked.",
    "L20",
  ),
  drill(
    "arp-inspection",
    "Read ARP inspection evidence",
    "5.7",
    "A client cannot resolve its gateway after DAI was enabled. Recall how to inspect VLAN validation counts before changing trust boundaries.",
    "show ip arp inspection statistics vlan 60",
    "Vlan      Forwarded        Dropped\n60        42               5",
    "This condensed illustrative output shows forwarded and dropped inspections. Counters alone do not identify the exact offending endpoint or prove malicious intent. Correlate bindings, logs, static-host policy, and controlled tests.",
    "Correlate dropped ARP traffic with valid bindings and the configured validation policy.",
    "L20",
  ),
  drill(
    "qos-policy",
    "Inspect per-hop queue treatment",
    "4.7",
    "A voice class is marked, but quality worsens during congestion. Recall how to inspect the attached output policy and its class counters on a supported IOS platform.",
    "show policy-map interface GigabitEthernet0/1",
    "GigabitEthernet0/1\n Service-policy output: BRANCH-QOS\n  Class-map: VOICE\n    Match: dscp ef\n    Priority: 20 (%)\n  Class-map: class-default\n    Total drops: 18",
    "This is condensed illustrative policy evidence, not a universal output template. The voice class matches EF and receives configured priority treatment. Default-class drops indicate congestion evidence to correlate with traffic rate and queue behavior; markings alone do not create capacity.",
    "Identify attachment, class match, scheduled treatment, and congestion counters.",
  ),
]
