import { expect, test } from "@playwright/test"
const fixture = "http://127.0.0.1:54321"
test.beforeEach(async ({ request }) => { await request.post(`${fixture}/__test/config`, { data: {} }) })
test.afterEach(async ({ request }) => { await request.post(`${fixture}/__test/config`, { data: {} }) })

test("choose routes and trace packet flow accessibly at phone width without recording progress", async ({ page, request }) => {
  await page.setViewportSize({ width: 360, height: 780 })
  await page.goto("/exercises/routing")
  await expect(page.getByRole("table", { name: /installed routes/i })).toBeVisible()
  const routeChoice = page.getByRole("radio", { name: "10.40.8.0/24 via 198.51.100.1", exact: true })
  await routeChoice.focus()
  await page.keyboard.press("Space")
  await page.getByRole("button", { name: "Check decision", exact: true }).click()
  await expect(page.getByRole("status")).toContainText("Correct.")
  await page.getByRole("button", { name: "Next case", exact: true }).click()
  await page.getByRole("radio", { name: "0.0.0.0/0 via 203.0.113.9", exact: true }).check()
  await page.getByRole("button", { name: "Check decision", exact: true }).click()
  await page.getByRole("button", { name: "Next case", exact: true }).click()
  await page.getByRole("radio", { name: /No matching route/ }).check()
  await page.getByRole("button", { name: "Check decision", exact: true }).click()
  await expect(page.getByRole("status")).toContainText("No listed prefix contains")
  await page.getByRole("button", { name: "Packet-flow choices", exact: true }).click()
  await page.getByRole("radio", { name: /ARP for 192.0.2.20/ }).check()
  await page.getByRole("button", { name: "Check decision", exact: true }).click()
  await expect(page.getByRole("list", { name: "Packet path in order" })).toContainText("A broadcasts an ARP request")
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(360)
  await expect(page.getByRole("link", { name: "Objective 3.2 guide and references" })).toBeVisible()
  const requests = await (await request.get(`${fixture}/__test/requests`)).json()
  expect(requests.some((item: { table: string; method: string }) => item.method !== "GET" && ["topic_progress", "lab_progress", "quiz_attempts", "study_sessions"].includes(item.table))).toBe(false)
})
